// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFb0JEEFKVaP3dbIESAmcatG0vNsUi_I',
    appId: '1:640782524560:web:b78582b861d0a5707a7815',
    messagingSenderId: '640782524560',
    projectId: 'taskmanager-265d0',
    authDomain: 'taskmanager-265d0.firebaseapp.com',
    storageBucket: 'taskmanager-265d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA567diQT-nwhCPktwoQvWp2ZReTM_Ly9I',
    appId: '1:640782524560:android:3def149ce2c8044c7a7815',
    messagingSenderId: '640782524560',
    projectId: 'taskmanager-265d0',
    storageBucket: 'taskmanager-265d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_eVxXsrwmIF5kghfmjHetiovkpvRf0A',
    appId: '1:640782524560:ios:4ef5e740c34be2927a7815',
    messagingSenderId: '640782524560',
    projectId: 'taskmanager-265d0',
    storageBucket: 'taskmanager-265d0.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN_eVxXsrwmIF5kghfmjHetiovkpvRf0A',
    appId: '1:640782524560:ios:4ef5e740c34be2927a7815',
    messagingSenderId: '640782524560',
    projectId: 'taskmanager-265d0',
    storageBucket: 'taskmanager-265d0.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdFb0JEEFKVaP3dbIESAmcatG0vNsUi_I',
    appId: '1:640782524560:web:b3ab0202b66e51c77a7815',
    messagingSenderId: '640782524560',
    projectId: 'taskmanager-265d0',
    authDomain: 'taskmanager-265d0.firebaseapp.com',
    storageBucket: 'taskmanager-265d0.firebasestorage.app',
  );
}
